name = "Newb Evermist Renewed[1.1.0]"
version = [1, 1, 0]
min_supported_mc_version = [1, 26, 40]
description = '''
§bThis shader offers a visual experience similar to the BSL shaders. Support 1.26.50+  
§7- Only Work Whit Minecraft Patch, Mb loader and BetterRenderDragon.
%v
§3https://newb-shader.devendrn.com/
''' # %w = patch warning, %v = version
authors = ["I'am Alex", "devendrn"]
url = "https://newb-shader.devendrn.com/"
uuid = "ad8dce61-4b6c-428a-a358-4da26e3a99ae" # Use https://www.uuidgenerator.net/version4
materials = ["Actor", "ActorGlint", "ActorMultiTexture", "Clouds", "EndSky", "ItemInHandColor", "ItemInHandColorGlint", "ItemInHandTextured", "RenderChunk","Sky", "Stars", "SunMoon", "Weather"]

[info] 
copyright = '''
Copyright © 2026 %a, and "Newb Shader" Contributors

This compiled "Newb Shader" resource pack (source code: https://github.com/devendrn/newb-x-mcbe under MIT License) is licensed under CC BY-ND 4.0 (https://creativecommons.org/licenses/by-nd/4.0/). Redistribute only unmodified copies with proper attribution to "Newb Shader" and variant creators (if any). Do not distribute derivatives.

You can compile the shader from source and distribute the result under your own terms (compatible with the MIT License).

Contact (Discord Server): https://discord.gg/newb-community-844591537430069279
''' # %a = authors
credits = '''
'''

# subpacks are arranged in left to right order
# right-most subpack is enabled by default
[[subpack]]
define = "REALISTIC_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§b§oRealistic Clouds
'''



[[subpack]]
define = "BOX_CLOUDS"
materials = ["Clouds", "RenderChunk"]
description = '''
§b§oDefault
'''
